<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Autoload namespaces
 *
 * @package car-dealer-helper
 */

// autoload_namespaces.php @generated by Composer.

$vendor_dir = dirname( dirname( __FILE__ ) );
$base_dir   = dirname( $vendor_dir );

return array(
	'Google_Service_' => array( $vendor_dir . '/google/apiclient-services/src' ),
	'Google_'         => array( $vendor_dir . '/google/apiclient/src' ),
);
