<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Autoload psr4
 *
 * @package car-dealer-helper
 */

// autoload_psr4.php @generated by Composer.

$vendor_dir = dirname( dirname( __FILE__ ) );
$base_dir   = dirname( $vendor_dir );

return array(
	'phpseclib\\'           => array( $vendor_dir . '/phpseclib/phpseclib/phpseclib' ),
	'Psr\\Log\\'            => array( $vendor_dir . '/psr/log/Psr/Log' ),
	'Psr\\Http\\Message\\'  => array( $vendor_dir . '/psr/http-message/src' ),
	'Psr\\Cache\\'          => array( $vendor_dir . '/psr/cache/src' ),
	'Monolog\\'             => array( $vendor_dir . '/monolog/monolog/src/Monolog' ),
	'GuzzleHttp\\Psr7\\'    => array( $vendor_dir . '/guzzlehttp/psr7/src' ),
	'GuzzleHttp\\Promise\\' => array( $vendor_dir . '/guzzlehttp/promises/src' ),
	'GuzzleHttp\\'          => array( $vendor_dir . '/guzzlehttp/guzzle/src' ),
	'Google\\Auth\\'        => array( $vendor_dir . '/google/auth/src' ),
	'Firebase\\JWT\\'       => array( $vendor_dir . '/firebase/php-jwt/src' ),
);
