<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Autoload classmap
 *
 * @package car-dealer-helper
 */

// autoload_classmap.php @generated by Composer.

$vendor_dir = dirname( dirname( __FILE__ ) );
$base_dir   = dirname( $vendor_dir );

return array(
	'Google\\Auth\\ApplicationDefaultCredentials'          => $vendor_dir . '/google/auth/src/ApplicationDefaultCredentials.php',
	'Google\\Auth\\CacheTrait'                             => $vendor_dir . '/google/auth/src/CacheTrait.php',
	'Google\\Auth\\CredentialsLoader'                      => $vendor_dir . '/google/auth/src/CredentialsLoader.php',
	'Google\\Auth\\Credentials\\AppIdentityCredentials'    => $vendor_dir . '/google/auth/src/Credentials/AppIdentityCredentials.php',
	'Google\\Auth\\Credentials\\GCECredentials'            => $vendor_dir . '/google/auth/src/Credentials/GCECredentials.php',
	'Google\\Auth\\Credentials\\IAMCredentials'            => $vendor_dir . '/google/auth/src/Credentials/IAMCredentials.php',
	'Google\\Auth\\Credentials\\ServiceAccountCredentials' => $vendor_dir . '/google/auth/src/Credentials/ServiceAccountCredentials.php',
	'Google\\Auth\\Credentials\\ServiceAccountJwtAccessCredentials' => $vendor_dir . '/google/auth/src/Credentials/ServiceAccountJwtAccessCredentials.php',
	'Google\\Auth\\Credentials\\UserRefreshCredentials'    => $vendor_dir . '/google/auth/src/Credentials/UserRefreshCredentials.php',
	'Google\\Auth\\FetchAuthTokenInterface'                => $vendor_dir . '/google/auth/src/FetchAuthTokenInterface.php',
	'Google\\Auth\\HttpHandler\\Guzzle5HttpHandler'        => $vendor_dir . '/google/auth/src/HttpHandler/Guzzle5HttpHandler.php',
	'Google\\Auth\\HttpHandler\\Guzzle6HttpHandler'        => $vendor_dir . '/google/auth/src/HttpHandler/Guzzle6HttpHandler.php',
	'Google\\Auth\\HttpHandler\\HttpHandlerFactory'        => $vendor_dir . '/google/auth/src/HttpHandler/HttpHandlerFactory.php',
	'Google\\Auth\\Middleware\\AuthTokenMiddleware'        => $vendor_dir . '/google/auth/src/Middleware/AuthTokenMiddleware.php',
	'Google\\Auth\\Middleware\\ScopedAccessTokenMiddleware' => $vendor_dir . '/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php',
	'Google\\Auth\\Middleware\\SimpleMiddleware'           => $vendor_dir . '/google/auth/src/Middleware/SimpleMiddleware.php',
	'Google\\Auth\\OAuth2'                                 => $vendor_dir . '/google/auth/src/OAuth2.php',
	'Google\\Auth\\Subscriber\\AuthTokenSubscriber'        => $vendor_dir . '/google/auth/src/Subscriber/AuthTokenSubscriber.php',
	'Google\\Auth\\Subscriber\\ScopedAccessTokenSubscriber' => $vendor_dir . '/google/auth/src/Subscriber/ScopedAccessTokenSubscriber.php',
	'Google\\Auth\\Subscriber\\SimpleSubscriber'           => $vendor_dir . '/google/auth/src/Subscriber/SimpleSubscriber.php',
	'Google_Service_Exception'                             => $vendor_dir . '/google/apiclient/src/Google/Service/Exception.php',
	'Google_Service_Resource'                              => $vendor_dir . '/google/apiclient/src/Google/Service/Resource.php',
);
