<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Autoload file
 *
 * @package car-dealer-helper
 */

// autoload_files.php @generated by Composer.

$vendor_dir = dirname( dirname( __FILE__ ) );
$base_dir   = dirname( $vendor_dir );

return array(
	'a0edc8309cc5e1d60e3047b5df6b7052' => $vendor_dir . '/guzzlehttp/psr7/src/functions_include.php',
	'c964ee0ededf28c96ebd9db5099ef910' => $vendor_dir . '/guzzlehttp/promises/src/functions_include.php',
	'37a3dc5111fe8f707ab4c132ef1dbc62' => $vendor_dir . '/guzzlehttp/guzzle/src/functions_include.php',
	'decc78cc4436b1292c6c0d151b19445c' => $vendor_dir . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
);
