<?php
/**
 * Autoload
 *
 * @package car-dealer-helper/functions
 */

// autoload.php @generated by Composer.

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit385b81b594b8370645f7d3a89cc12586::getLoader();
