<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Cardealer Visual Composer iconpicker flaticon.
 *
 * @package car-dealer-helper/functions
 */

/**
 * Flaticon Icon Picker.
 *
 * @param string $icons .
 */
function cdhl_vc_iconpicker_type_flaticon( $icons ) {
	// Add custom icons to array.
	$icons['Car Icons'] = array(
		array( 'glyph-icon flaticon-air-conditioning' => 'Air Conditioning' ),
		array( 'glyph-icon flaticon-alloy-wheel' => 'Alloy Wheel' ),
		array( 'glyph-icon flaticon-badge' => 'Badge' ),
		array( 'glyph-icon flaticon-battery' => 'Battery' ),
		array( 'glyph-icon flaticon-beetle' => 'Beetle' ),
		array( 'glyph-icon flaticon-calculator' => 'Calculator' ),
		array( 'glyph-icon flaticon-cancel' => 'Cancel' ),
		array( 'glyph-icon flaticon-car' => 'Car' ),
		array( 'glyph-icon flaticon-car-1' => 'Car 1' ),
		array( 'glyph-icon flaticon-car-2' => 'Car 2' ),
		array( 'glyph-icon flaticon-car-repair' => 'Car Repair' ),
		array( 'glyph-icon flaticon-car-wash' => 'Car Wash' ),
		array( 'glyph-icon flaticon-checked' => 'Checked' ),
		array( 'glyph-icon flaticon-circle' => 'Circle' ),
		array( 'glyph-icon flaticon-clock' => 'Clock' ),
		array( 'glyph-icon flaticon-clock-1' => 'Clock 1' ),
		array( 'glyph-icon flaticon-commerce' => 'Commerce' ),
		array( 'glyph-icon flaticon-compass' => 'Compass' ),
		array( 'glyph-icon flaticon-coupon' => 'Coupon' ),
		array( 'glyph-icon flaticon-cup' => 'Cup' ),
		array( 'glyph-icon flaticon-cup-1' => 'Cup 1' ),
		array( 'glyph-icon flaticon-cup-2' => 'Cup 2' ),
		array( 'glyph-icon flaticon-cursor' => 'Cursor' ),
		array( 'glyph-icon flaticon-customer-service' => 'Customer Service' ),
		array( 'glyph-icon flaticon-diagnostic' => 'Diagnostic' ),
		array( 'glyph-icon flaticon-disc-brake' => 'Disc Brake' ),
		array( 'glyph-icon flaticon-electrical-service' => 'Electrical Service' ),
		array( 'glyph-icon flaticon-engine' => 'Engnie' ),
		array( 'glyph-icon flaticon-envelope' => 'Envelope' ),
		array( 'glyph-icon flaticon-exhaust-pipe' => 'Exhaust Pipe' ),
		array( 'glyph-icon flaticon-flag' => 'Flag' ),
		array( 'glyph-icon flaticon-garbage' => 'Garbage' ),
		array( 'glyph-icon flaticon-gas-station' => 'Gas Station' ),
		array( 'glyph-icon flaticon-gearstick' => 'Gear Stick' ),
		array( 'glyph-icon flaticon-giftbox' => 'giftbox' ),
		array( 'glyph-icon flaticon-ignition' => 'Ignition' ),
		array( 'glyph-icon flaticon-information' => 'Information' ),
		array( 'glyph-icon flaticon-inspection' => 'Inspection' ),
		array( 'glyph-icon flaticon-interface' => 'Interface' ),
		array( 'glyph-icon flaticon-interface-1' => 'Interface 1' ),
		array( 'glyph-icon flaticon-jeep' => 'Jeep' ),
		array( 'glyph-icon flaticon-key' => 'Key' ),
		array( 'glyph-icon flaticon-left-arrow' => 'Left Arrow' ),
		array( 'glyph-icon flaticon-left-arrow-1' => 'Left Arrow 1' ),
		array( 'glyph-icon flaticon-loupe' => 'Loupe' ),
		array( 'glyph-icon flaticon-maintenance' => 'Maintenance' ),
		array( 'glyph-icon flaticon-mechanic' => 'Mechanic' ),
		array( 'glyph-icon flaticon-medal' => 'Medal' ),
		array( 'glyph-icon flaticon-menu' => 'Menu' ),
		array( 'glyph-icon flaticon-minivan' => 'Minivan' ),
		array( 'glyph-icon flaticon-minus' => 'Minus' ),
		array( 'glyph-icon flaticon-mouse' => 'Mouse' ),
		array( 'glyph-icon flaticon-multimedia' => 'Multimedia' ),
		array( 'glyph-icon flaticon-oil' => 'Oil' ),
		array( 'glyph-icon flaticon-padlock' => 'Padlock' ),
		array( 'glyph-icon flaticon-painting' => 'Painiting' ),
		array( 'glyph-icon flaticon-pencil' => 'Pencil' ),
		array( 'glyph-icon flaticon-pin' => 'Pin' ),
		array( 'glyph-icon flaticon-piston' => 'Piston' ),
		array( 'glyph-icon flaticon-placeholder' => 'Place holder' ),
		array( 'glyph-icon flaticon-play-video' => 'Play Video' ),
		array( 'glyph-icon flaticon-plus' => 'Plus' ),
		array( 'glyph-icon flaticon-price-tag' => 'Price Tag' ),
		array( 'glyph-icon flaticon-radiator' => 'radiator' ),
		array( 'glyph-icon flaticon-reparation' => 'Reparation' ),
		array( 'glyph-icon flaticon-ribbon' => 'Ribbon' ),
		array( 'glyph-icon flaticon-right-arrow' => 'Right Arrow' ),
		array( 'glyph-icon flaticon-right-arrow-1' => 'Right Arrow 1' ),
		array( 'glyph-icon flaticon-shopping-cart' => 'Shopping Cart' ),
		array( 'glyph-icon flaticon-shopping-cart-1' => 'Shopping Cart 1' ),
		array( 'glyph-icon flaticon-signs' => 'Signs' ),
		array( 'glyph-icon flaticon-social' => 'Social' ),
		array( 'glyph-icon flaticon-speedometer' => 'Speed Meter' ),
		array( 'glyph-icon flaticon-speedometer-1' => 'Speedometer' ),
		array( 'glyph-icon flaticon-speedometer-circular-outlined-tool-symbol' => 'Speedometer Circular Outlined' ),
		array( 'glyph-icon flaticon-star' => 'Star' ),
		array( 'glyph-icon flaticon-station-wagon' => 'Station Wagon' ),
		array( 'glyph-icon flaticon-steering-wheel' => 'Steering Wheel' ),
		array( 'glyph-icon flaticon-stroller' => 'Stroller' ),
		array( 'glyph-icon flaticon-suspension' => 'Suspension' ),
		array( 'glyph-icon flaticon-technology' => 'Technology' ),
		array( 'glyph-icon flaticon-technology-1' => 'Technogy 1' ),
		array( 'glyph-icon flaticon-tire' => 'Tire' ),
		array( 'glyph-icon flaticon-tire-1' => 'Tire 1' ),
		array( 'glyph-icon flaticon-trailer' => 'Trailer' ),
		array( 'glyph-icon flaticon-transport' => 'Transport' ),
		array( 'glyph-icon flaticon-transport-1' => 'Transport 1' ),
		array( 'glyph-icon flaticon-transport-2' => 'Transport 2' ),
		array( 'glyph-icon flaticon-transport-3' => 'Transport 3' ),
		array( 'glyph-icon flaticon-transport-4' => 'Transport 4' ),
		array( 'glyph-icon flaticon-transport-5' => 'Transport 5' ),
		array( 'glyph-icon flaticon-transport-6' => 'Transport 6' ),
		array( 'glyph-icon flaticon-transport-7' => 'Transport 7' ),
		array( 'glyph-icon flaticon-transport-8' => 'Transport 8' ),
		array( 'glyph-icon flaticon-transport-9' => 'Transport 9' ),
		array( 'glyph-icon flaticon-travel' => 'travel' ),
		array( 'glyph-icon flaticon-volskwagen-van' => 'Volswagen Van' ),
		array( 'glyph-icon flaticon-wallet' => 'Wallet' ),
		array( 'glyph-icon flaticon-wheel-alignment' => 'Wheel Alignment' ),
		array( 'glyph-icon flaticon-windshield' => 'Wind Shield' ),
	);
	// Return icons.
	return $icons;
}
add_filter( 'vc_iconpicker-type-flaticon', 'cdhl_vc_iconpicker_type_flaticon' );
